export const THEMES = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
  "dim",
  "nord",
  "sunset",
];

export const THEME_LABELS = {
  light: "Clair",
  dark: "Sombre",
  cupcake: "Cupcake",
  bumblebee: "Bourdon",
  emerald: "Émeraude",

  corporate: "Corporate",
  synthwave: "Synthwave",
  retro: "Rétro",
  cyberpunk: "Cyberpunk",
  valentine: "Saint-Valentin",
  halloween: "Halloween",
  garden: "Jardin",
  forest: "Forêt",
  aqua: "Aqua",
  lofi: "Lofi",
  pastel: "Pastel",
  fantasy: "Fantaisie",
  wireframe: "Wireframe",
  black: "Noir",
  luxury: "Luxe",
  dracula: "Dracula",
  cmyk: "CMJN",
  autumn: "Automne",
  business: "Business",
  acid: "Acid",
  lemonade: "Limonade",
  night: "Nuit",
  coffee: "Café",
  winter: "Hiver",
  dim: "Obscur",
  nord: "Nord",
  sunset: "Coucher de soleil",
};
